# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_name',
        ),
    ]
