# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160907_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
