# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('hire_date', models.DateField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='dept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.Employees'),
        ),
    ]
